title: Dr JAY GURUBALAN
description: Emergency Medicine Physician | Systems Researcher | Computational Biologist 
theme: minima

header_pages:
  - research.md
  - projects.md
  - computational.md
  - systems.md
  - publications.md
  - cv.md
