title: Dr. Jayadevan Gurubalan
description: Physician | Systems Researcher | Computational Biologist
theme: minima

header_pages:
  - research.md
  - computational.md
  - systems.md
  - publications.md
  - cv.md
