title: J A Y   G U R U B A L A N
description: Emergency Medicine Physician | Systems Researcher | Computational Biologist 
theme: minima

header_pages:
  - projects.md
  - publications.md
  - research_works.md
  - independant_projects.md
  - cv.md
